-- Seed: medical exam specialties + catalog (generated)
-- Re-run safe: upserts by primary/unique keys

insert into public.medical_exam_specialties (id, name_ar, name_en, sort_order) values
  ('internal_medicine', 'الباطنة العامة', 'Internal Medicine', 1),
  ('cardiology', 'القلب', 'Cardiology', 2),
  ('pulmonology', 'الصدر', 'Pulmonology', 3),
  ('gastroenterology', 'الجهاز الهضمي والكبد', 'Gastroenterology & Hepatology', 4),
  ('nephrology', 'الكلى والمسالك البولية', 'Nephrology & Urology', 5),
  ('endocrinology', 'الغدد الصماء', 'Endocrinology', 6),
  ('rheumatology', 'الروماتيزم', 'Rheumatology', 7),
  ('neurology', 'الأعصاب', 'Neurology', 8),
  ('orthopedics', 'العظام', 'Orthopedics', 9),
  ('obgyn', 'النساء والتوليد', 'Obstetrics & Gynecology', 10),
  ('pediatrics', 'الأطفال', 'Pediatrics', 11),
  ('dermatology', 'الجلدية', 'Dermatology', 12),
  ('ent', 'الأنف والأذن والحنجرة', 'ENT', 13),
  ('ophthalmology', 'العيون', 'Ophthalmology', 14),
  ('dentistry', 'الأسنان', 'Dentistry', 15),
  ('general_surgery', 'الجراحة العامة', 'General Surgery', 16),
  ('oncology', 'الأورام', 'Oncology', 17),
  ('hematology', 'أمراض الدم', 'Hematology', 18),
  ('infectious_disease', 'الأمراض المعدية', 'Infectious Diseases', 19),
  ('psychiatry', 'الطب النفسي', 'Psychiatry', 20),
  ('neurosurgery', 'جراحة المخ والأعصاب', 'Neurosurgery', 21),
  ('plastic_surgery', 'جراحة التجميل', 'Plastic Surgery', 22),
  ('nutrition', 'التغذية والسمنة', 'Nutrition & Obesity', 23)
on conflict (id) do update set name_ar = excluded.name_ar, name_en = excluded.name_en, sort_order = excluded.sort_order;

insert into public.medical_exams (
  specialty_id, exam_kind, category, name_ar, name_en, code, requires_fasting, result_tat_hours, doctor_notes, sort_order
) values
  ('internal_medicine', 'lab', 'lab', 'صورة دم كاملة', 'CBC', 'LOINC-58410-2', false, 6, null, 1),
  ('internal_medicine', 'lab', 'lab', 'سرعة الترسيب', 'ESR', 'LOINC-4537-7', false, 6, null, 2),
  ('internal_medicine', 'lab', 'lab', 'البروتين التفاعلي C', 'CRP', 'LOINC-1988-5', false, 6, null, 3),
  ('internal_medicine', 'lab', 'lab', 'سكر صائم', 'Fasting Blood Sugar (FBS)', 'LOINC-1558-6', true, 6, null, 4),
  ('internal_medicine', 'lab', 'lab', 'سكر عشوائي', 'Random Blood Sugar (RBS)', 'LOINC-2339-0', false, 2, null, 5),
  ('internal_medicine', 'lab', 'lab', 'السكر التراكمي', 'HbA1c', 'LOINC-4548-4', false, 24, null, 6),
  ('internal_medicine', 'lab', 'lab', 'وظائف الكلى (يوريا، كرياتينين)', 'Kidney Function (Urea, Creatinine)', 'CF-KFT', false, 12, null, 7),
  ('internal_medicine', 'lab', 'lab', 'وظائف الكبد', 'Liver Function (ALT, AST, Albumin, Bilirubin)', 'CF-LFT', false, 12, null, 8),
  ('internal_medicine', 'lab', 'lab', 'دهون الدم', 'Lipid Profile', 'CF-LIPID', true, 12, null, 9),
  ('internal_medicine', 'lab', 'lab', 'الأملاح (صوديوم، بوتاسيوم، كلوريد)', 'Electrolytes (Na, K, Cl)', 'CF-ELECTROLYTES', false, 6, null, 10),
  ('internal_medicine', 'lab', 'lab', 'حمض اليوريك', 'Uric Acid', 'LOINC-3084-1', false, 12, null, 11),
  ('internal_medicine', 'lab', 'lab', 'الكالسيوم', 'Calcium', 'LOINC-17861-6', false, 12, null, 12),
  ('internal_medicine', 'lab', 'lab', 'الماغنسيوم', 'Magnesium', 'LOINC-19123-9', false, 12, null, 13),
  ('internal_medicine', 'lab', 'lab', 'الفوسفور', 'Phosphorus', 'LOINC-2777-1', false, 12, null, 14),
  ('internal_medicine', 'lab', 'lab', 'فيتامين د', 'Vitamin D', 'LOINC-1989-3', false, 48, null, 15),
  ('internal_medicine', 'lab', 'lab', 'فيتامين ب12', 'Vitamin B12', 'LOINC-2132-9', false, 48, null, 16),
  ('internal_medicine', 'lab', 'lab', 'الفيريتين', 'Ferritin', 'LOINC-2276-4', false, 24, null, 17),
  ('internal_medicine', 'lab', 'lab', 'مقارنة الحديد', 'Iron Profile', 'CF-IRON-PROFILE', false, 24, null, 18),
  ('internal_medicine', 'lab', 'lab', 'زمن البروثرومبين / INR', 'PT, INR', 'CF-PT-INR', false, 6, null, 19),
  ('internal_medicine', 'lab', 'lab', 'زمن التخثر الجزئي', 'PTT', 'LOINC-3173-2', false, 6, null, 20),
  ('internal_medicine', 'imaging', 'radiology', 'أشعة صدر', 'Chest X-ray', 'CF-CXR', false, 4, null, 21),
  ('internal_medicine', 'imaging', 'radiology', 'سونار بطن', 'Abdominal Ultrasound', 'CF-US-ABD', true, 4, 'يفضل صيام 6–8 ساعات', 22),
  ('internal_medicine', 'imaging', 'radiology', 'مقطعية بطن', 'CT Abdomen', 'CF-CT-ABD', false, 24, null, 23),
  ('internal_medicine', 'imaging', 'radiology', 'رنين بطن', 'MRI Abdomen', 'CF-MRI-ABD', false, 48, null, 24),
  ('cardiology', 'lab', 'lab', 'التروبونين', 'Troponin', 'LOINC-10839-9', false, 2, 'مستعجل عند الاشتباه باحتشاء', 1),
  ('cardiology', 'lab', 'lab', 'إنزيم القلب CK-MB', 'CK-MB', 'LOINC-13969-1', false, 6, null, 2),
  ('cardiology', 'lab', 'lab', 'BNP', 'BNP', 'LOINC-30934-4', false, 12, null, 3),
  ('cardiology', 'lab', 'lab', 'دي دايمر', 'D-Dimer', 'LOINC-48065-7', false, 6, null, 4),
  ('cardiology', 'lab', 'lab', 'دهون الدم', 'Lipid Profile', 'CF-LIPID', true, 12, null, 5),
  ('cardiology', 'lab', 'lab', 'PT/INR', 'PT/INR', 'CF-PT-INR', false, 6, null, 6),
  ('cardiology', 'lab', 'lab', 'الأملاح', 'Electrolytes', 'CF-ELECTROLYTES', false, 6, null, 7),
  ('cardiology', 'cardiac', 'functional', 'رسم قلب', 'ECG', 'CF-ECG', false, 1, null, 8),
  ('cardiology', 'cardiac', 'functional', 'إيكو قلب', 'Echocardiography', 'CF-ECHO', false, 4, null, 9),
  ('cardiology', 'cardiac', 'functional', 'هولتر رسم قلب', 'Holter ECG', 'CF-HOLTER', false, 24, null, 10),
  ('cardiology', 'functional', 'functional', 'اختبار جهد', 'Stress Test', 'CF-STRESS', false, 4, null, 11),
  ('cardiology', 'imaging', 'radiology', 'مقطعية شرايين تاجية', 'Coronary CT', 'CF-CT-CORONARY', false, 24, null, 12),
  ('cardiology', 'imaging', 'radiology', 'رنين قلب', 'Cardiac MRI', 'CF-MRI-CARDIAC', false, 48, null, 13),
  ('cardiology', 'procedure', 'functional', 'قسطرة قلب', 'Cardiac Catheterization', 'CF-CATH', false, 24, 'إجراء تدخلي — تحضير خاص', 14),
  ('pulmonology', 'lab', 'lab', 'صورة دم كاملة', 'CBC', 'LOINC-58410-2', false, 6, null, 1),
  ('pulmonology', 'lab', 'lab', 'البروتين التفاعلي C', 'CRP', 'LOINC-1988-5', false, 6, null, 2),
  ('pulmonology', 'lab', 'lab', 'سرعة الترسيب', 'ESR', 'LOINC-4537-7', false, 6, null, 3),
  ('pulmonology', 'lab', 'lab', 'مزرعة بلغم', 'Sputum Culture', 'CF-SPUTUM-CULTURE', false, 72, null, 4),
  ('pulmonology', 'lab', 'lab', 'صبغة زيل نلسن للبلغم', 'Sputum AFB', 'CF-SPUTUM-AFB', false, 48, null, 5),
  ('pulmonology', 'lab', 'lab', 'جين إكسبرت', 'GeneXpert', 'CF-GENEXPERT', false, 24, null, 6),
  ('pulmonology', 'lab', 'lab', 'غازات الدم الشرياني', 'ABG', 'CF-ABG', false, 1, null, 7),
  ('pulmonology', 'lab', 'lab', 'دي دايمر', 'D-Dimer', 'LOINC-48065-7', false, 6, null, 8),
  ('pulmonology', 'lab', 'lab', 'مسحة كورونا PCR', 'COVID PCR', 'CF-COVID-PCR', false, 24, null, 9),
  ('pulmonology', 'lab', 'lab', 'إنفلونزا PCR', 'Influenza PCR', 'CF-FLU-PCR', false, 24, null, 10),
  ('pulmonology', 'imaging', 'radiology', 'أشعة صدر', 'Chest X-ray', 'CF-CXR', false, 4, null, 11),
  ('pulmonology', 'imaging', 'radiology', 'مقطعية صدر عالية الدقة', 'HRCT Chest', 'CF-HRCT', false, 24, null, 12),
  ('pulmonology', 'imaging', 'radiology', 'مقطعية صدر', 'CT Chest', 'CF-CT-CHEST', false, 24, null, 13),
  ('pulmonology', 'functional', 'functional', 'وظائف تنفس', 'Pulmonary Function Test (PFT)', 'CF-PFT', false, 4, null, 14),
  ('pulmonology', 'endoscopy', 'radiology', 'منظار قصبات', 'Bronchoscopy', 'CF-BRONCHO', false, 24, null, 15),
  ('gastroenterology', 'lab', 'lab', 'وظائف الكبد', 'Liver Function', 'CF-LFT', false, 12, null, 1),
  ('gastroenterology', 'lab', 'lab', 'فيروس الكبد B سطحي', 'HBsAg', 'LOINC-5196-1', false, 24, null, 2),
  ('gastroenterology', 'lab', 'lab', 'أجسام مضادة لفيروس الكبد C', 'HCV Ab', 'LOINC-16128-1', false, 24, null, 3),
  ('gastroenterology', 'lab', 'lab', 'حمض نووي فيروس الكبد B', 'HBV DNA', 'CF-HBV-DNA', false, 72, null, 4),
  ('gastroenterology', 'lab', 'lab', 'فيروس الكبد C PCR', 'HCV PCR', 'CF-HCV-PCR', false, 72, null, 5),
  ('gastroenterology', 'lab', 'lab', 'تحليل براز', 'Stool Analysis', 'CF-STOOL', false, 12, null, 6),
  ('gastroenterology', 'lab', 'lab', 'مزرعة براز', 'Stool Culture', 'CF-STOOL-CULTURE', false, 72, null, 7),
  ('gastroenterology', 'lab', 'lab', 'دم خفي في البراز', 'Occult Blood', 'LOINC-2335-8', false, 24, null, 8),
  ('gastroenterology', 'lab', 'lab', 'الأميليز', 'Amylase', 'LOINC-1798-8', false, 6, null, 9),
  ('gastroenterology', 'lab', 'lab', 'الليباز', 'Lipase', 'LOINC-3040-3', false, 6, null, 10),
  ('gastroenterology', 'lab', 'lab', 'تحليل حساسية القمح', 'Celiac Profile', 'CF-CELIAC', false, 48, null, 11),
  ('gastroenterology', 'lab', 'lab', 'جرثومة المعدة في البراز', 'Helicobacter pylori Antigen', 'CF-HPYLORI-AG', false, 24, null, 12),
  ('gastroenterology', 'imaging', 'radiology', 'سونار بطن', 'Abdominal Ultrasound', 'CF-US-ABD', true, 4, null, 13),
  ('gastroenterology', 'imaging', 'radiology', 'مقطعية بطن', 'CT Abdomen', 'CF-CT-ABD', false, 24, null, 14),
  ('gastroenterology', 'imaging', 'radiology', 'رنين بطن', 'MRI Abdomen', 'CF-MRI-ABD', false, 48, null, 15),
  ('gastroenterology', 'imaging', 'radiology', 'رنين للقنوات المرارية', 'MRCP', 'CF-MRCP', true, 48, null, 16),
  ('gastroenterology', 'endoscopy', 'radiology', 'منظار معدة', 'Upper GI Endoscopy', 'CF-EGD', true, 4, 'صيام 8 ساعات', 17),
  ('gastroenterology', 'endoscopy', 'radiology', 'منظار قولون', 'Colonoscopy', 'CF-COLONOSCOPY', false, 4, 'تحضير قولون مطلوب', 18),
  ('nephrology', 'lab', 'lab', 'تحليل بول', 'Urine Analysis', 'CF-UA', false, 4, null, 1),
  ('nephrology', 'lab', 'lab', 'مزرعة بول', 'Urine Culture', 'CF-UC', false, 48, null, 2),
  ('nephrology', 'lab', 'lab', 'بروتين بول 24 ساعة', '24-hour Urine Protein', 'CF-UPROTEIN-24H', false, 24, null, 3),
  ('nephrology', 'lab', 'lab', 'الكرياتينين', 'Creatinine', 'LOINC-2160-0', false, 6, null, 4),
  ('nephrology', 'lab', 'lab', 'اليوريا', 'Urea', 'LOINC-3094-0', false, 6, null, 5),
  ('nephrology', 'lab', 'lab', 'الأملاح', 'Electrolytes', 'CF-ELECTROLYTES', false, 6, null, 6),
  ('nephrology', 'lab', 'lab', 'حمض اليوريك', 'Uric Acid', 'LOINC-3084-1', false, 12, null, 7),
  ('nephrology', 'lab', 'lab', 'مؤشر البروستاتا PSA', 'PSA', 'LOINC-2857-1', false, 24, 'للرجال', 8),
  ('nephrology', 'imaging', 'radiology', 'سونار كلى ومسالك', 'KUB Ultrasound', 'CF-US-KUB', false, 4, null, 9),
  ('nephrology', 'imaging', 'radiology', 'مقطعية كلى ومسالك', 'CT KUB', 'CF-CT-KUB', false, 24, null, 10),
  ('nephrology', 'imaging', 'radiology', 'أشعة صبغية للمسالك', 'IVP', 'CF-IVP', false, 24, null, 11),
  ('nephrology', 'endoscopy', 'radiology', 'منظار مثانة', 'Cystoscopy', 'CF-CYSTO', false, 4, null, 12),
  ('nephrology', 'imaging', 'radiology', 'دوبلر كلى', 'Renal Doppler', 'CF-DOPPLER-RENAL', false, 4, null, 13),
  ('endocrinology', 'lab', 'lab', 'هرمون الغدة الدرقية TSH', 'TSH', 'LOINC-3016-3', false, 24, null, 1),
  ('endocrinology', 'lab', 'lab', 'T3 حر', 'FT3', 'LOINC-3051-0', false, 24, null, 2),
  ('endocrinology', 'lab', 'lab', 'T4 حر', 'FT4', 'LOINC-3024-7', false, 24, null, 3),
  ('endocrinology', 'lab', 'lab', 'السكر التراكمي', 'HbA1c', 'LOINC-4548-4', false, 24, null, 4),
  ('endocrinology', 'lab', 'lab', 'إنسولين صائم', 'Fasting Insulin', 'LOINC-20448-7', true, 24, null, 5),
  ('endocrinology', 'lab', 'lab', 'الكورتيزول', 'Cortisol', 'LOINC-2143-6', false, 24, 'حدد توقيت السحب (صباحي/مسائي)', 6),
  ('endocrinology', 'lab', 'lab', 'ACTH', 'ACTH', 'LOINC-2141-0', false, 48, null, 7),
  ('endocrinology', 'lab', 'lab', 'هرمون الغدة الجار درقية', 'PTH', 'LOINC-2731-8', false, 24, null, 8),
  ('endocrinology', 'lab', 'lab', 'فيتامين د', 'Vitamin D', 'LOINC-1989-3', false, 48, null, 9),
  ('endocrinology', 'lab', 'lab', 'التستوستيرون', 'Testosterone', 'LOINC-2986-8', false, 24, null, 10),
  ('endocrinology', 'lab', 'lab', 'الإستروجين', 'Estrogen', 'CF-ESTROGEN', false, 24, null, 11),
  ('endocrinology', 'lab', 'lab', 'البرولاكتين', 'Prolactin', 'LOINC-2842-3', false, 24, null, 12),
  ('endocrinology', 'lab', 'lab', 'LH', 'LH', 'LOINC-10501-5', false, 24, null, 13),
  ('endocrinology', 'lab', 'lab', 'FSH', 'FSH', 'LOINC-15067-2', false, 24, null, 14),
  ('endocrinology', 'imaging', 'radiology', 'سونار غدة درقية', 'Thyroid Ultrasound', 'CF-US-THYROID', false, 4, null, 15),
  ('endocrinology', 'imaging', 'radiology', 'رنين غدة نخامية', 'Pituitary MRI', 'CF-MRI-PITUITARY', false, 48, null, 16),
  ('endocrinology', 'imaging', 'radiology', 'قياس كثافة العظام', 'DEXA Scan', 'CF-DEXA', false, 24, null, 17),
  ('rheumatology', 'lab', 'lab', 'سرعة الترسيب', 'ESR', 'LOINC-4537-7', false, 6, null, 1),
  ('rheumatology', 'lab', 'lab', 'البروتين التفاعلي C', 'CRP', 'LOINC-1988-5', false, 6, null, 2),
  ('rheumatology', 'lab', 'lab', 'عامل الروماتويد', 'RF', 'LOINC-11572-5', false, 24, null, 3),
  ('rheumatology', 'lab', 'lab', 'Anti-CCP', 'Anti-CCP', 'LOINC-33935-9', false, 48, null, 4),
  ('rheumatology', 'lab', 'lab', 'ANA', 'ANA', 'LOINC-42254-3', false, 48, null, 5),
  ('rheumatology', 'lab', 'lab', 'Anti-dsDNA', 'Anti-dsDNA', 'LOINC-5130-0', false, 48, null, 6),
  ('rheumatology', 'lab', 'lab', 'لوحة ENA', 'ENA Profile', 'CF-ENA', false, 72, null, 7),
  ('rheumatology', 'lab', 'lab', 'HLA-B27', 'HLA-B27', 'LOINC-26043-6', false, 72, null, 8),
  ('rheumatology', 'lab', 'lab', 'مكمل C3', 'C3', 'LOINC-4485-9', false, 24, null, 9),
  ('rheumatology', 'lab', 'lab', 'مكمل C4', 'C4', 'LOINC-4498-2', false, 24, null, 10),
  ('rheumatology', 'lab', 'lab', 'حمض اليوريك', 'Uric Acid', 'LOINC-3084-1', false, 12, null, 11),
  ('rheumatology', 'imaging', 'radiology', 'أشعة مفاصل', 'X-ray Joints', 'CF-XR-JOINT', false, 4, null, 12),
  ('rheumatology', 'imaging', 'radiology', 'رنين المفصل العجزي الحرقفي', 'MRI Sacroiliac', 'CF-MRI-SI', false, 48, null, 13),
  ('rheumatology', 'imaging', 'radiology', 'رنين عمود فقري', 'MRI Spine', 'CF-MRI-SPINE', false, 48, null, 14),
  ('rheumatology', 'imaging', 'radiology', 'سونار عضلي هيكلي', 'Musculoskeletal Ultrasound', 'CF-US-MSK', false, 4, null, 15),
  ('neurology', 'lab', 'lab', 'فيتامين ب12', 'Vitamin B12', 'LOINC-2132-9', false, 48, null, 1),
  ('neurology', 'lab', 'lab', 'فيتامين د', 'Vitamin D', 'LOINC-1989-3', false, 48, null, 2),
  ('neurology', 'lab', 'lab', 'الأملاح', 'Electrolytes', 'CF-ELECTROLYTES', false, 6, null, 3),
  ('neurology', 'lab', 'lab', 'إنزيم العضلات CK', 'CK', 'LOINC-2157-6', false, 12, null, 4),
  ('neurology', 'lab', 'lab', 'لوحة مناعية ذاتية', 'Autoimmune Profile', 'CF-AUTOIMMUNE', false, 72, null, 5),
  ('neurology', 'imaging', 'radiology', 'رنين مخ', 'MRI Brain', 'CF-MRI-BRAIN', false, 48, null, 6),
  ('neurology', 'imaging', 'radiology', 'رنين عمود فقري', 'MRI Spine', 'CF-MRI-SPINE', false, 48, null, 7),
  ('neurology', 'imaging', 'radiology', 'مقطعية مخ', 'CT Brain', 'CF-CT-BRAIN', false, 4, null, 8),
  ('neurology', 'functional', 'functional', 'رسم مخ كهربائي', 'EEG', 'CF-EEG', false, 24, null, 9),
  ('neurology', 'functional', 'functional', 'رسم عضلات', 'EMG', 'CF-EMG', false, 24, null, 10),
  ('neurology', 'functional', 'functional', 'دراسة توصيل الأعصاب', 'Nerve Conduction Study', 'CF-NCS', false, 24, null, 11),
  ('neurology', 'imaging', 'radiology', 'دوبلر شريان سباتي', 'Carotid Doppler', 'CF-DOPPLER-CAROTID', false, 4, null, 12),
  ('orthopedics', 'lab', 'lab', 'الكالسيوم', 'Calcium', 'LOINC-17861-6', false, 12, null, 1),
  ('orthopedics', 'lab', 'lab', 'فيتامين د', 'Vitamin D', 'LOINC-1989-3', false, 48, null, 2),
  ('orthopedics', 'lab', 'lab', 'الفوسفور', 'Phosphorus', 'LOINC-2777-1', false, 12, null, 3),
  ('orthopedics', 'lab', 'lab', 'الفوسفاتاز القلوي', 'ALP', 'LOINC-6768-6', false, 12, null, 4),
  ('orthopedics', 'lab', 'lab', 'سرعة الترسيب', 'ESR', 'LOINC-4537-7', false, 6, null, 5),
  ('orthopedics', 'lab', 'lab', 'البروتين التفاعلي C', 'CRP', 'LOINC-1988-5', false, 6, null, 6),
  ('orthopedics', 'imaging', 'radiology', 'أشعة عادية', 'X-ray', 'CF-XR', false, 2, null, 7),
  ('orthopedics', 'imaging', 'radiology', 'مقطعية عظام', 'CT Bone', 'CF-CT-BONE', false, 24, null, 8),
  ('orthopedics', 'imaging', 'radiology', 'رنين مفصل', 'MRI Joint', 'CF-MRI-JOINT', false, 48, null, 9),
  ('orthopedics', 'imaging', 'radiology', 'مسح عظام', 'Bone Scan', 'CF-BONE-SCAN', false, 48, null, 10),
  ('orthopedics', 'imaging', 'radiology', 'قياس كثافة العظام', 'DEXA', 'CF-DEXA', false, 24, null, 11),
  ('obgyn', 'lab', 'lab', 'تحليل حمل β-hCG', 'β-hCG', 'LOINC-21198-7', false, 6, null, 1),
  ('obgyn', 'lab', 'lab', 'صورة دم كاملة', 'CBC', 'LOINC-58410-2', false, 6, null, 2),
  ('obgyn', 'lab', 'lab', 'فصيلة الدم', 'Blood Group', 'LOINC-882-1', false, 6, null, 3),
  ('obgyn', 'lab', 'lab', 'TORCH', 'TORCH', 'CF-TORCH', false, 72, null, 4),
  ('obgyn', 'lab', 'lab', 'مسحة عنق الرحم', 'Pap Smear', 'CF-PAP', false, 72, 'باثولوجي', 5),
  ('obgyn', 'lab', 'lab', 'فيروس الورم الحليمي', 'HPV', 'CF-HPV', false, 72, null, 6),
  ('obgyn', 'lab', 'lab', 'مخزون المبيض AMH', 'AMH', 'LOINC-79059-5', false, 48, null, 7),
  ('obgyn', 'lab', 'lab', 'FSH', 'FSH', 'LOINC-15067-2', false, 24, null, 8),
  ('obgyn', 'lab', 'lab', 'LH', 'LH', 'LOINC-10501-5', false, 24, null, 9),
  ('obgyn', 'lab', 'lab', 'الإستراديول', 'Estradiol', 'LOINC-2243-4', false, 24, null, 10),
  ('obgyn', 'lab', 'lab', 'البروجستيرون', 'Progesterone', 'LOINC-2839-9', false, 24, null, 11),
  ('obgyn', 'lab', 'lab', 'البرولاكتين', 'Prolactin', 'LOINC-2842-3', false, 24, null, 12),
  ('obgyn', 'imaging', 'radiology', 'سونار حوض', 'Pelvic Ultrasound', 'CF-US-PELVIC', false, 4, null, 13),
  ('obgyn', 'imaging', 'radiology', 'سونار مهبلي', 'TVS', 'CF-US-TVS', false, 4, null, 14),
  ('obgyn', 'imaging', 'radiology', 'متابعة تبويض', 'Folliculometry', 'CF-FOLLICULOMETRY', false, 2, null, 15),
  ('obgyn', 'imaging', 'radiology', 'أشعة صبغية للرحم', 'HSG', 'CF-HSG', false, 24, null, 16),
  ('obgyn', 'functional', 'functional', 'مراقبة نبض الجنين NST', 'NST', 'CF-NST', false, 1, null, 17),
  ('obgyn', 'imaging', 'radiology', 'سونار حمل', 'Obstetric Ultrasound', 'CF-US-OB', false, 2, null, 18),
  ('pediatrics', 'lab', 'lab', 'صورة دم كاملة', 'CBC', 'LOINC-58410-2', false, 6, null, 1),
  ('pediatrics', 'lab', 'lab', 'البروتين التفاعلي C', 'CRP', 'LOINC-1988-5', false, 6, null, 2),
  ('pediatrics', 'lab', 'lab', 'سرعة الترسيب', 'ESR', 'LOINC-4537-7', false, 6, null, 3),
  ('pediatrics', 'lab', 'lab', 'تحليل براز', 'Stool Analysis', 'CF-STOOL', false, 12, null, 4),
  ('pediatrics', 'lab', 'lab', 'تحليل بول', 'Urine Analysis', 'CF-UA', false, 4, null, 5),
  ('pediatrics', 'lab', 'lab', 'مزرعة دم', 'Blood Culture', 'CF-BLOOD-CULTURE', false, 72, null, 6),
  ('pediatrics', 'lab', 'lab', 'الأملاح', 'Electrolytes', 'CF-ELECTROLYTES', false, 6, null, 7),
  ('pediatrics', 'lab', 'lab', 'البليروبين', 'Bilirubin', 'LOINC-1975-2', false, 6, null, 8),
  ('pediatrics', 'lab', 'lab', 'نقص G6PD', 'G6PD', 'LOINC-2356-4', false, 48, null, 9),
  ('pediatrics', 'lab', 'lab', 'مسح حديثي الولادة', 'Neonatal Screening', 'CF-NBS', false, 72, null, 10),
  ('pediatrics', 'imaging', 'radiology', 'أشعة صدر', 'Chest X-ray', 'CF-CXR', false, 4, null, 11),
  ('pediatrics', 'imaging', 'radiology', 'سونار بطن', 'Abdominal Ultrasound', 'CF-US-ABD', false, 4, null, 12),
  ('pediatrics', 'imaging', 'radiology', 'سونار مخ (يافوخ)', 'Brain Ultrasound', 'CF-US-BRAIN', false, 4, null, 13),
  ('pediatrics', 'cardiac', 'functional', 'إيكو قلب', 'Echocardiography', 'CF-ECHO', false, 4, null, 14),
  ('dermatology', 'lab', 'lab', 'صورة دم كاملة', 'CBC', 'LOINC-58410-2', false, 6, null, 1),
  ('dermatology', 'lab', 'lab', 'ANA', 'ANA', 'LOINC-42254-3', false, 48, null, 2),
  ('dermatology', 'lab', 'lab', 'الجلوبيولين IgE', 'IgE', 'LOINC-19113-0', false, 24, null, 3),
  ('dermatology', 'lab', 'lab', 'اختبارات حساسية', 'Allergy Tests', 'CF-ALLERGY', false, 48, null, 4),
  ('dermatology', 'lab', 'lab', 'كشط جلدي', 'Skin Scraping', 'CF-SKIN-SCRAPE', false, 24, null, 5),
  ('dermatology', 'lab', 'lab', 'مزرعة فطريات', 'Fungal Culture', 'CF-FUNGAL-CULTURE', false, 168, null, 6),
  ('dermatology', 'functional', 'functional', 'اختبار لاصق للحساسية', 'Patch Test', 'CF-PATCH', false, 72, null, 7),
  ('dermatology', 'procedure', 'functional', 'منظار جلدي', 'Dermoscopy', 'CF-DERMOSCOPY', false, 1, null, 8),
  ('dermatology', 'biopsy', 'pathology', 'عينة جلد', 'Skin Biopsy', 'CF-SKIN-BX', false, 120, null, 9),
  ('ent', 'lab', 'lab', 'مزرعة حلق', 'Throat Culture', 'CF-THROAT-CULTURE', false, 48, null, 1),
  ('ent', 'lab', 'lab', 'صورة دم كاملة', 'CBC', 'LOINC-58410-2', false, 6, null, 2),
  ('ent', 'lab', 'lab', 'البروتين التفاعلي C', 'CRP', 'LOINC-1988-5', false, 6, null, 3),
  ('ent', 'functional', 'functional', 'مقياس سمع', 'Audiometry', 'CF-AUDIO', false, 2, null, 4),
  ('ent', 'functional', 'functional', 'قياس طبلة الأذن', 'Tympanometry', 'CF-TYMPANO', false, 2, null, 5),
  ('ent', 'endoscopy', 'radiology', 'منظار أنف', 'Nasal Endoscopy', 'CF-NASAL-ENDO', false, 1, null, 6),
  ('ent', 'imaging', 'radiology', 'مقطعية جيوب أنفية', 'CT Sinuses', 'CF-CT-SINUS', false, 24, null, 7),
  ('ent', 'imaging', 'radiology', 'رنين رقبة', 'MRI Neck', 'CF-MRI-NECK', false, 48, null, 8),
  ('ophthalmology', 'functional', 'functional', 'حدة الإبصار', 'Visual Acuity', 'CF-VA', false, 1, null, 1),
  ('ophthalmology', 'functional', 'functional', 'قياس النظر', 'Refraction', 'CF-REFRACTION', false, 1, null, 2),
  ('ophthalmology', 'functional', 'functional', 'OCT شبكية', 'OCT', 'CF-OCT', false, 2, null, 3),
  ('ophthalmology', 'functional', 'functional', 'تصوير قاع العين', 'Fundus Photography', 'CF-FUNDUS', false, 2, null, 4),
  ('ophthalmology', 'functional', 'functional', 'تصوير بالصبغة للعين', 'Fluorescein Angiography', 'CF-FA', false, 4, null, 5),
  ('ophthalmology', 'functional', 'functional', 'مجال إبصار', 'Visual Field', 'CF-VF', false, 2, null, 6),
  ('ophthalmology', 'functional', 'functional', 'طبوغرافيا القرنية', 'Corneal Topography', 'CF-CORNEAL-TOPO', false, 2, null, 7),
  ('ophthalmology', 'imaging', 'radiology', 'سونار عين B-Scan', 'B-Scan Ultrasound', 'CF-US-BSCAN', false, 2, null, 8),
  ('dentistry', 'imaging', 'radiology', 'أشعة حول الذروة', 'Periapical X-ray', 'CF-XR-PA', false, 1, null, 1),
  ('dentistry', 'imaging', 'radiology', 'أشعة جناحية', 'Bitewing X-ray', 'CF-XR-BW', false, 1, null, 2),
  ('dentistry', 'imaging', 'radiology', 'بانوراما أسنان', 'OPG', 'CF-OPG', false, 2, null, 3),
  ('dentistry', 'imaging', 'radiology', 'مقطعية مخروطية للأسنان', 'CBCT', 'CF-CBCT', false, 4, null, 4),
  ('dentistry', 'lab', 'lab', 'صورة دم كاملة', 'CBC', 'LOINC-58410-2', false, 6, 'عند الحاجة قبل إجراء', 5),
  ('dentistry', 'lab', 'lab', 'اختبارات نزف', 'Bleeding Profile', 'CF-BLEEDING', false, 6, null, 6),
  ('dentistry', 'lab', 'lab', 'سكر الدم', 'Blood Sugar', 'LOINC-2339-0', false, 2, null, 7),
  ('dentistry', 'lab', 'lab', 'PT/INR', 'PT/INR', 'CF-PT-INR', false, 6, null, 8),
  ('dentistry', 'lab', 'lab', 'فيروس الكبد B', 'HBV', 'LOINC-5196-1', false, 24, null, 9),
  ('dentistry', 'lab', 'lab', 'فيروس الكبد C', 'HCV', 'LOINC-16128-1', false, 24, null, 10),
  ('general_surgery', 'lab', 'lab', 'صورة دم كاملة', 'CBC', 'LOINC-58410-2', false, 6, null, 1),
  ('general_surgery', 'lab', 'lab', 'PT', 'PT', 'LOINC-5902-2', false, 6, null, 2),
  ('general_surgery', 'lab', 'lab', 'INR', 'INR', 'LOINC-6301-6', false, 6, null, 3),
  ('general_surgery', 'lab', 'lab', 'PTT', 'PTT', 'LOINC-3173-2', false, 6, null, 4),
  ('general_surgery', 'lab', 'lab', 'فصيلة الدم', 'Blood Group', 'LOINC-882-1', false, 6, null, 5),
  ('general_surgery', 'lab', 'lab', 'وظائف الكلى', 'Kidney Function', 'CF-KFT', false, 12, null, 6),
  ('general_surgery', 'lab', 'lab', 'وظائف الكبد', 'Liver Function', 'CF-LFT', false, 12, null, 7),
  ('general_surgery', 'lab', 'lab', 'سكر الدم', 'Blood Sugar', 'LOINC-2339-0', false, 2, null, 8),
  ('general_surgery', 'lab', 'lab', 'الأملاح', 'Electrolytes', 'CF-ELECTROLYTES', false, 6, null, 9),
  ('general_surgery', 'imaging', 'radiology', 'سونار', 'Ultrasound', 'CF-US', false, 4, null, 10),
  ('general_surgery', 'imaging', 'radiology', 'مقطعية', 'CT', 'CF-CT', false, 24, null, 11),
  ('general_surgery', 'imaging', 'radiology', 'رنين', 'MRI', 'CF-MRI', false, 48, null, 12),
  ('general_surgery', 'imaging', 'radiology', 'أشعة عادية', 'X-ray', 'CF-XR', false, 2, null, 13),
  ('oncology', 'lab', 'lab', 'صورة دم كاملة', 'CBC', 'LOINC-58410-2', false, 6, null, 1),
  ('oncology', 'lab', 'lab', 'دلالات أورام', 'Tumor Markers (CEA, AFP, CA125, CA19-9, PSA, CA15-3)', 'CF-TUMOR-MARKERS', false, 48, null, 2),
  ('oncology', 'lab', 'lab', 'LDH', 'LDH', 'LOINC-2532-0', false, 12, null, 3),
  ('oncology', 'imaging', 'radiology', 'مقطعية', 'CT', 'CF-CT', false, 24, null, 4),
  ('oncology', 'imaging', 'radiology', 'رنين', 'MRI', 'CF-MRI', false, 48, null, 5),
  ('oncology', 'imaging', 'radiology', 'PET-CT', 'PET-CT', 'CF-PET-CT', false, 72, 'تحضير خاص + صيام', 6),
  ('oncology', 'imaging', 'radiology', 'مسح عظام', 'Bone Scan', 'CF-BONE-SCAN', false, 48, null, 7),
  ('hematology', 'lab', 'lab', 'صورة دم كاملة', 'CBC', 'LOINC-58410-2', false, 6, null, 1),
  ('hematology', 'lab', 'lab', 'فيلم دم طرفي', 'Peripheral Blood Film', 'CF-PBF', false, 24, null, 2),
  ('hematology', 'lab', 'lab', 'الشبكيات', 'Reticulocyte Count', 'LOINC-14196-0', false, 12, null, 3),
  ('hematology', 'lab', 'lab', 'الفيريتين', 'Ferritin', 'LOINC-2276-4', false, 24, null, 4),
  ('hematology', 'lab', 'lab', 'مقارنة الحديد', 'Iron Profile', 'CF-IRON-PROFILE', false, 24, null, 5),
  ('hematology', 'lab', 'lab', 'فيتامين ب12', 'Vitamin B12', 'LOINC-2132-9', false, 48, null, 6),
  ('hematology', 'lab', 'lab', 'حمض الفوليك', 'Folate', 'LOINC-2284-8', false, 48, null, 7),
  ('hematology', 'biopsy', 'pathology', 'شفط نخاع عظم', 'Bone Marrow Aspiration', 'CF-BMA', false, 120, null, 8),
  ('hematology', 'lab', 'lab', 'اختبار كومبس', 'Coombs Test', 'CF-COOMBS', false, 24, null, 9),
  ('hematology', 'lab', 'lab', 'فصل الهيموجلوبين', 'Hemoglobin Electrophoresis', 'CF-HB-EP', false, 72, null, 10),
  ('infectious_disease', 'lab', 'lab', 'مزرعة دم', 'Blood Culture', 'CF-BLOOD-CULTURE', false, 72, null, 1),
  ('infectious_disease', 'lab', 'lab', 'مزرعة بول', 'Urine Culture', 'CF-UC', false, 48, null, 2),
  ('infectious_disease', 'lab', 'lab', 'مزرعة براز', 'Stool Culture', 'CF-STOOL-CULTURE', false, 72, null, 3),
  ('infectious_disease', 'lab', 'lab', 'مزرعة بلغم', 'Sputum Culture', 'CF-SPUTUM-CULTURE', false, 72, null, 4),
  ('infectious_disease', 'lab', 'lab', 'HIV', 'HIV', 'LOINC-56888-1', false, 24, null, 5),
  ('infectious_disease', 'lab', 'lab', 'فيروس الكبد B', 'HBsAg', 'LOINC-5196-1', false, 24, null, 6),
  ('infectious_disease', 'lab', 'lab', 'فيروس الكبد C', 'HCV', 'LOINC-16128-1', false, 24, null, 7),
  ('infectious_disease', 'lab', 'lab', 'حمى الضنك', 'Dengue', 'CF-DENGUE', false, 24, null, 8),
  ('infectious_disease', 'lab', 'lab', 'الملاريا', 'Malaria', 'CF-MALARIA', false, 6, null, 9),
  ('infectious_disease', 'lab', 'lab', 'التيفوئيد', 'Typhoid', 'CF-TYPHOID', false, 24, null, 10),
  ('infectious_disease', 'lab', 'lab', 'البروسيلا', 'Brucella', 'CF-BRUCELLA', false, 48, null, 11),
  ('psychiatry', 'lab', 'lab', 'صورة دم كاملة', 'CBC', 'LOINC-58410-2', false, 6, 'قبل بدء العلاج أو لاستبعاد سبب عضوي', 1),
  ('psychiatry', 'lab', 'lab', 'TSH', 'TSH', 'LOINC-3016-3', false, 24, null, 2),
  ('psychiatry', 'lab', 'lab', 'فيتامين ب12', 'Vitamin B12', 'LOINC-2132-9', false, 48, null, 3),
  ('psychiatry', 'lab', 'lab', 'فيتامين د', 'Vitamin D', 'LOINC-1989-3', false, 48, null, 4),
  ('psychiatry', 'lab', 'lab', 'الأملاح', 'Electrolytes', 'CF-ELECTROLYTES', false, 6, null, 5),
  ('psychiatry', 'lab', 'lab', 'وظائف الكبد', 'Liver Function', 'CF-LFT', false, 12, null, 6),
  ('psychiatry', 'lab', 'lab', 'وظائف الكلى', 'Kidney Function', 'CF-KFT', false, 12, null, 7),
  ('psychiatry', 'lab', 'lab', 'سكر الدم', 'Blood Sugar', 'LOINC-2339-0', false, 2, null, 8),
  ('neurosurgery', 'imaging', 'radiology', 'مقطعية مخ', 'CT Brain', 'CF-CT-BRAIN', false, 4, null, 1),
  ('neurosurgery', 'imaging', 'radiology', 'رنين مخ', 'MRI Brain', 'CF-MRI-BRAIN', false, 48, null, 2),
  ('neurosurgery', 'imaging', 'radiology', 'رنين عمود فقري', 'MRI Spine', 'CF-MRI-SPINE', false, 48, null, 3),
  ('neurosurgery', 'imaging', 'radiology', 'تصوير أوعية المخ', 'Cerebral Angiography', 'CF-CEREBRAL-ANGIO', false, 24, null, 4),
  ('neurosurgery', 'imaging', 'radiology', 'أشعة عمود فقري', 'Spine X-ray', 'CF-XR-SPINE', false, 2, null, 5),
  ('neurosurgery', 'lab', 'lab', 'صورة دم كاملة', 'CBC', 'LOINC-58410-2', false, 6, null, 6),
  ('neurosurgery', 'lab', 'lab', 'اختبارات تجلط', 'Coagulation Profile', 'CF-COAG', false, 6, null, 7),
  ('neurosurgery', 'lab', 'lab', 'الأملاح', 'Electrolytes', 'CF-ELECTROLYTES', false, 6, null, 8),
  ('plastic_surgery', 'lab', 'lab', 'صورة دم كاملة', 'CBC', 'LOINC-58410-2', false, 6, null, 1),
  ('plastic_surgery', 'lab', 'lab', 'PT/INR', 'PT/INR', 'CF-PT-INR', false, 6, null, 2),
  ('plastic_surgery', 'lab', 'lab', 'سكر الدم', 'Blood Sugar', 'LOINC-2339-0', false, 2, null, 3),
  ('plastic_surgery', 'lab', 'lab', 'دلالات فيروسية', 'Viral Markers', 'CF-VIRAL-MARKERS', false, 24, null, 4),
  ('plastic_surgery', 'lab', 'lab', 'وظائف الكلى', 'Kidney Function', 'CF-KFT', false, 12, null, 5),
  ('plastic_surgery', 'lab', 'lab', 'وظائف الكبد', 'Liver Function', 'CF-LFT', false, 12, null, 6),
  ('nutrition', 'lab', 'lab', 'السكر التراكمي', 'HbA1c', 'LOINC-4548-4', false, 24, null, 1),
  ('nutrition', 'lab', 'lab', 'دهون الدم', 'Lipid Profile', 'CF-LIPID', true, 12, null, 2),
  ('nutrition', 'lab', 'lab', 'TSH', 'TSH', 'LOINC-3016-3', false, 24, null, 3),
  ('nutrition', 'lab', 'lab', 'فيتامين د', 'Vitamin D', 'LOINC-1989-3', false, 48, null, 4),
  ('nutrition', 'lab', 'lab', 'فيتامين ب12', 'Vitamin B12', 'LOINC-2132-9', false, 48, null, 5),
  ('nutrition', 'lab', 'lab', 'الفيريتين', 'Ferritin', 'LOINC-2276-4', false, 24, null, 6),
  ('nutrition', 'lab', 'lab', 'الحديد', 'Iron', 'LOINC-2498-4', false, 24, null, 7),
  ('nutrition', 'lab', 'lab', 'الزنك', 'Zinc', 'LOINC-5763-4', false, 48, null, 8),
  ('nutrition', 'lab', 'lab', 'الماغنسيوم', 'Magnesium', 'LOINC-19123-9', false, 12, null, 9)
on conflict (specialty_id, name_en) do update set
  exam_kind = excluded.exam_kind,
  category = excluded.category,
  name_ar = excluded.name_ar,
  code = excluded.code,
  requires_fasting = excluded.requires_fasting,
  result_tat_hours = excluded.result_tat_hours,
  doctor_notes = excluded.doctor_notes,
  sort_order = excluded.sort_order,
  is_active = true;

-- Seeded 23 specialties, 278 exams